--
INSERT INTO authors (firstName, lastName) VALUES ('Janush', 'Kowalski');
INSERT INTO authors (firstName, lastName) VALUES ('Mściwój', 'Hulaka');
INSERT INTO authors (firstName, lastName) VALUES ('Wiesław', 'Wiercidziura');
INSERT INTO authors (firstName, lastName) VALUES ('Marzena', 'Koralik');
--
INSERT INTO categories (name, description) VALUES ('motoryzacja', 'o autach motocyklach etc');
INSERT INTO categories (name, description) VALUES ('przyroda', 'kwiatki i zwierzątka');
INSERT INTO categories (name, description) VALUES ('sport', 'ruch to zdrowie');

INSERT INTO articles (title, author_id, content, draft) VALUES ('Silniki parowe', 1," Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque id porttitor justo, eget convallis sem. Vestibulum ipsum nunc, accumsan et bibendum in, commodo a orci. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas sed porttitor risus. Integer tincidunt commodo lorem, a pretium nibh lobortis et. In rhoncus tristique velit et efficitur. Vivamus tempus enim ac felis dapibus venenatis. Curabitur ut lobortis turpis, eget convallis mi. In hac habitasse platea dictumst. Mauris pulvinar lacinia massa sed lacinia. Cras mi lacus, blandit nec mattis in, pulvinar cursus justo. In auctor justo sed malesuada sodales. Integer aliquet, nibh sed luctus semper, diam dolor euismod eros, vitae fermentum est libero elementum enim. Integer ac nisl orci. Suspendisse potenti. Maecenas eu magna facilisis, gravida mi et, eleifend nibh. Aenean lacinia ultricies turpis sed gravida. Morbi ullamcorper pretium tellus nec semper. Ut hendrerit nibh erat, ac tincidunt leo auctor sed. Donec eleifend mauris scelerisque sem luctus tristique. Nam consequat ut velit vitae fringilla. Sed cursus, tortor in varius molestie, ex tortor volutpat massa, id finibus ligula tortor vel elit. ", 0);
INSERT INTO articles (title, author_id, content, draft) VALUES ('Drzewa i ich cienie', 2," Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque id porttitor justo, eget convallis sem. Vestibulum ipsum nunc, accumsan et bibendum in, commodo a orci. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas sed porttitor risus. Integer tincidunt commodo lorem, a pretium nibh lobortis et. In rhoncus tristique velit et efficitur. Vivamus tempus enim ac felis dapibus venenatis. Curabitur ut lobortis turpis, eget convallis mi. In hac habitasse platea dictumst. Mauris pulvinar lacinia massa sed lacinia. Cras mi lacus, blandit nec mattis in, pulvinar cursus justo. In auctor justo sed malesuada sodales. Integer aliquet, nibh sed luctus semper, diam dolor euismod eros, vitae fermentum est libero elementum enim. Integer ac nisl orci. Suspendisse potenti. Maecenas eu magna facilisis, gravida mi et, eleifend nibh. Aenean lacinia ultricies turpis sed gravida. Morbi ullamcorper pretium tellus nec semper. Ut hendrerit nibh erat, ac tincidunt leo auctor sed. Donec eleifend mauris scelerisque sem luctus tristique. Nam consequat ut velit vitae fringilla. Sed cursus, tortor in varius molestie, ex tortor volutpat massa, id finibus ligula tortor vel elit. ", 0);
INSERT INTO articles (title, author_id, content, draft) VALUES ('Magiczne właściwości krzaków w ogródku', 4," Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque id porttitor justo, eget convallis sem. Vestibulum ipsum nunc, accumsan et bibendum in, commodo a orci. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas sed porttitor risus. Integer tincidunt commodo lorem, a pretium nibh lobortis et. In rhoncus tristique velit et efficitur. Vivamus tempus enim ac felis dapibus venenatis. Curabitur ut lobortis turpis, eget convallis mi. In hac habitasse platea dictumst. Mauris pulvinar lacinia massa sed lacinia. Cras mi lacus, blandit nec mattis in, pulvinar cursus justo. In auctor justo sed malesuada sodales. Integer aliquet, nibh sed luctus semper, diam dolor euismod eros, vitae fermentum est libero elementum enim. Integer ac nisl orci. Suspendisse potenti. Maecenas eu magna facilisis, gravida mi et, eleifend nibh. Aenean lacinia ultricies turpis sed gravida. Morbi ullamcorper pretium tellus nec semper. Ut hendrerit nibh erat, ac tincidunt leo auctor sed. Donec eleifend mauris scelerisque sem luctus tristique. Nam consequat ut velit vitae fringilla. Sed cursus, tortor in varius molestie, ex tortor volutpat massa, id finibus ligula tortor vel elit. ", 0);
INSERT INTO articles (title, author_id, content, draft) VALUES ('Kubica by nie hamował', 3," Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque id porttitor justo, eget convallis sem. Vestibulum ipsum nunc, accumsan et bibendum in, commodo a orci. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas sed porttitor risus. Integer tincidunt commodo lorem, a pretium nibh lobortis et. In rhoncus tristique velit et efficitur. Vivamus tempus enim ac felis dapibus venenatis. Curabitur ut lobortis turpis, eget convallis mi. In hac habitasse platea dictumst. Mauris pulvinar lacinia massa sed lacinia. Cras mi lacus, blandit nec mattis in, pulvinar cursus justo. In auctor justo sed malesuada sodales. Integer aliquet, nibh sed luctus semper, diam dolor euismod eros, vitae fermentum est libero elementum enim. Integer ac nisl orci. Suspendisse potenti. Maecenas eu magna facilisis, gravida mi et, eleifend nibh. Aenean lacinia ultricies turpis sed gravida. Morbi ullamcorper pretium tellus nec semper. Ut hendrerit nibh erat, ac tincidunt leo auctor sed. Donec eleifend mauris scelerisque sem luctus tristique. Nam consequat ut velit vitae fringilla. Sed cursus, tortor in varius molestie, ex tortor volutpat massa, id finibus ligula tortor vel elit. ", 0);
INSERT INTO articles (title, author_id, content, draft) VALUES ('Samochód kontra drzewa', 1," Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque id porttitor justo, eget convallis sem. Vestibulum ipsum nunc, accumsan et bibendum in, commodo a orci. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas sed porttitor risus. Integer tincidunt commodo lorem, a pretium nibh lobortis et. In rhoncus tristique velit et efficitur. Vivamus tempus enim ac felis dapibus venenatis. Curabitur ut lobortis turpis, eget convallis mi. In hac habitasse platea dictumst. Mauris pulvinar lacinia massa sed lacinia. Cras mi lacus, blandit nec mattis in, pulvinar cursus justo. In auctor justo sed malesuada sodales. Integer aliquet, nibh sed luctus semper, diam dolor euismod eros, vitae fermentum est libero elementum enim. Integer ac nisl orci. Suspendisse potenti. Maecenas eu magna facilisis, gravida mi et, eleifend nibh. Aenean lacinia ultricies turpis sed gravida. Morbi ullamcorper pretium tellus nec semper. Ut hendrerit nibh erat, ac tincidunt leo auctor sed. Donec eleifend mauris scelerisque sem luctus tristique. Nam consequat ut velit vitae fringilla. Sed cursus, tortor in varius molestie, ex tortor volutpat massa, id finibus ligula tortor vel elit. ", 0);
INSERT INTO articles (title, author_id, content, draft) VALUES ('Zawody w ścinaniu drzew motocyklem', 2," Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque id porttitor justo, eget convallis sem. Vestibulum ipsum nunc, accumsan et bibendum in, commodo a orci. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas sed porttitor risus. Integer tincidunt commodo lorem, a pretium nibh lobortis et. In rhoncus tristique velit et efficitur. Vivamus tempus enim ac felis dapibus venenatis. Curabitur ut lobortis turpis, eget convallis mi. In hac habitasse platea dictumst. Mauris pulvinar lacinia massa sed lacinia. Cras mi lacus, blandit nec mattis in, pulvinar cursus justo. In auctor justo sed malesuada sodales. Integer aliquet, nibh sed luctus semper, diam dolor euismod eros, vitae fermentum est libero elementum enim. Integer ac nisl orci. Suspendisse potenti. Maecenas eu magna facilisis, gravida mi et, eleifend nibh. Aenean lacinia ultricies turpis sed gravida. Morbi ullamcorper pretium tellus nec semper. Ut hendrerit nibh erat, ac tincidunt leo auctor sed. Donec eleifend mauris scelerisque sem luctus tristique. Nam consequat ut velit vitae fringilla. Sed cursus, tortor in varius molestie, ex tortor volutpat massa, id finibus ligula tortor vel elit. ", 0);

INSERT INTO articles_categories(Article_id, categories_id) VALUES (1, 1);
INSERT INTO articles_categories(Article_id, categories_id) VALUES (2, 2);
INSERT INTO articles_categories(Article_id, categories_id) VALUES (3, 2);
INSERT INTO articles_categories(Article_id, categories_id) VALUES (4, 1);
INSERT INTO articles_categories(Article_id, categories_id) VALUES (4, 3);
INSERT INTO articles_categories(Article_id, categories_id) VALUES (5, 1);
INSERT INTO articles_categories(Article_id, categories_id) VALUES (5, 2);
INSERT INTO articles_categories(Article_id, categories_id) VALUES (6, 1);
INSERT INTO articles_categories(Article_id, categories_id) VALUES (6, 2);
INSERT INTO articles_categories(Article_id, categories_id) VALUES (6, 3);